import { Layout } from '@/components/layout/Layout';
import '@/styles/global.css';

export const metadata = {
  title: 'Welcome to rgd-demo',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <Layout>{children}</Layout>
    </html>
  );
}
