import { Layout } from '@/components/layout/Layout';
import '@/styles/global.css'; // Changed to import the correct CSS file with theme variables
import { ThemeProvider } from '@/styles/theme/theme-provider';

export const metadata = {
  title: 'Welcome to rgd-demo',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body>
        <ThemeProvider>
          <Layout>{children}</Layout>
        </ThemeProvider>
      </body>
    </html>
  );
}
